let productos = [
  {
    id: 1,
    nombre: "Alimento Shulet Carassius para peces",
    categoria: "Alimento",
    cantidad: 1,
    desc: "Alimento balanceado de alta calidad para peces Carassius, de la marca Shulet.",
    precio: 1800,
    img: "../img/Alimento.webp",
  },
  {
    id: 2,
    nombre: "Alimento Proplan para perro adulto",
    categoria: "Alimento",
    cantidad: 1,
    desc: "Alimento balanceado de alta calidad para perros adultos, de la marca Proplan.",
    precio: 2900,
    img: "../img/Alimento2.webp",
  },
  {
    id: 3,
    nombre: "Alimento Whiskas para gatitos",
    categoria: "Alimento",
    cantidad: 1,
    desc: "Alimento balanceado de alta calidad para gatitos, de la marca Whiskas.",
    precio: 2500,
    img: "../img/Alimento3.png",
  },
  {
    id: 4,
    nombre: "Alimento Agility para perro adulto",
    categoria: "Alimento",
    cantidad: 1,
    desc: "Alimento balanceado de alta calidad para perros adultos, de la marca Agility.",
    precio: 3150,
    img: "../img/Alimento4.png",
  },
  {
    id: 5,
    nombre: "Bocaditos Tasty Snack para gato",
    categoria: "Alimento",
    cantidad: 1,
    desc: "Alimento complementario para gatos, compuesto por deliciosos bocaditos de la marca Tasty Snack.",
    precio: 1300,
    img: "../img/Alimento5.png",
  },
  {
    id: 6,
    nombre: "Alimento Royal Canin para perro",
    categoria: "Alimento",
    cantidad: 1,
    desc: "Alimento balanceado de alta calidad para perros adultos, de la marca Royal Canin.",
    precio: 3550,
    img: "../img/Alimento6.webp",
  },
  {
    id: 7,
    nombre: "Alimento Advance para perro adulto",
    categoria: "Alimento",
    cantidad: 1,
    desc: "Alimento balanceado de alta calidad para perros adultos, de la marca Advance.",
    precio: 2950,
    img: "../img/Alimento7.png",
  },
  {
    id: 8,
    nombre: "Alimento Excellent para gato",
    categoria: "Alimento",
    cantidad: 1,
    desc: "Alimento balanceado de alta calidad para gatos adultos, de la marca Purina.",
    precio: 2860,
    img: "../img/Alimento8.webp",
  },
  {
    id: 9,
    nombre: "Rascador de felpa para gatos",
    categoria: "Rascador",
    cantidad: 1,
    desc: "Rascador para gatos de alta calidad, cubierto de suave felpa para brindar mayor comodidad y diversión.",
    precio: 4800,
    img: "../img/Rascador.jpg",
  },
  {
    id: 10,
    nombre: "Rascador para la pared",
    categoria: "Rascador",
    cantidad: 1,
    desc: "Este rascador para gatos está diseñado para ser montado en la pared y ayudar a mantener a tu gato feliz y saludable mientras ahorras espacio en tu hogar.",
    precio: 2900,
    img: "../img/Rascador2.webp",
  },
  {
    id: 11,
    nombre: "Rascador tamaño grande",
    categoria: "Rascador",
    cantidad: 1,
    desc: "Este rascador para gatos es perfecto para gatos grandes o para aquellos que prefieren rascar en superficies más altas.",
    precio: 5250,
    img: "../img/Rascador3.jpg",
  },
  {
    id: 12,
    nombre: "Rascador de 3 pisos",
    categoria: "Rascador",
    cantidad: 1,
    desc: "Este rascador para gatos de tres pisos proporciona una experiencia completa de juego y descanso para tu gato.",
    precio: 7000,
    img: "../img/Rascador4.jpg",
  },
  {
    id: 13,
    nombre: "Rascador con camas",
    categoria: "Rascador",
    cantidad: 1,
    desc: "Este rascador para gatos está cubierto de felpa suave y cuenta con múltiples camas para que tu gato descanse cómodamente después de jugar.",
    precio: 6100,
    img: "../img/Rascador5.jpg",
  },
  {
    id: 14,
    nombre: "Rascador de felpa grande",
    categoria: "Rascador",
    cantidad: 1,
    desc: "Este rascador para gatos de gran tamaño está cubierto de felpa suave y ofrece una superficie amplia para que tu gato pueda rascar y jugar.",
    precio: 5900,
    img: "../img/Rascador6.webp",
  },
  {
    id: 15,
    nombre: "Rascador de 4 pisos",
    categoria: "Rascador",
    cantidad: 1,
    desc: "Este rascador para gatos de cuatro pisos cuenta con dos camas suaves y múltiples superficies de rascado para que tu gato se divierta y descanse.",
    precio: 11200,
    img: "../img/Rascador7.jpg",
  },
  {
    id: 16,
    nombre: "Rascador con plumas y bolitas",
    categoria: "Rascador",
    cantidad: 1,
    desc: "Este rascador para gatos cuenta con plumas y bolitas de lana colgantes que mantendrán a tu gato entretenido y feliz durante horas.",
    precio: 3900,
    img: "../img/Rascador8.jpg",
  },
  {
    id: 17,
    nombre: "Pelotitas para perros y gatos",
    categoria: "Juguete",
    cantidad: 1,
    desc: "Este juguete es perfecto para mantener a tu mascota activa y entretenida. La pelotita es ideal tanto para perros como para gatos",
    precio: 1800,
    img: "../img/Juguete.jpg",
  },
  {
    id: 18,
    nombre: "Hueso grande para perro",
    categoria: "Juguete",
    cantidad: 1,
    desc: "Si estás buscando un juguete para tu perro que sea resistente y duradero, este hueso grande es una excelente opción.",
    precio: 1000,
    img: "../img/Juguete2.jpg",
  },
  {
    id: 19,
    nombre: "Caña con plumas",
    categoria: "Juguete",
    cantidad: 1,
    desc: "Si tu gato es fanático de las plumas, esta caña es perfecta para él.  la caña está diseñada para ser resistente y duradera, por lo que podrás usarla por mucho tiempo.",
    precio: 950,
    img: "../img/Juguete3.webp",
  },
  {
    id: 20,
    nombre: "Raton electrico",
    categoria: "Juguete",
    cantidad: 1,
    desc: "Este juguete es ideal para aquellos gatos que aman cazar ratones, simula los movimientos de un ratón real, lo que mantendrá a tu gato entretenido y en forma.",
    precio: 2650,
    img: "../img/Juguete4.webp",
  },
  {
    id: 21,
    nombre: "Bolitas giratorias y ratones con resorte",
    categoria: "Juguete",
    cantidad: 1,
    desc: "Estas bolitas giratorias y ratones con resorte son una excelente opción para estimular el instinto cazador de tu gato. ",
    precio: 2600,
    img: "../img/Juguete5.jpg",
  },
  {
    id: 22,
    nombre: "Bola de goma totalmente resistente",
    categoria: "Juguete",
    cantidad: 1,
    desc: "Esta bola está diseñada para ser resistente y duradera, por lo que podrás jugar con tu perro durante mucho tiempo.",
    precio: 1300,
    img: "../img/Juguete6.jpg",
  },
  {
    id: 23,
    nombre: "Soga mulftiforma para perro",
    categoria: "Juguete",
    cantidad: 1,
    desc: "Esta soga está diseñada en diferentes formas y colores para mantener a tu perro entretenido y feliz",
    precio: 1000,
    img: "../img/Juguete7.jpg",
  },
  {
    id: 24,
    nombre: "Pelotita con plumas para gato",
    categoria: "Juguete",
    cantidad: 1,
    desc: "Estas pelotitas están diseñadas con plumas y materiales de alta calidad para mantener a tu gato activo y feliz",
    precio: 850,
    img: "../img/Juguete8.jpg",
  },
];

// Convertir a JSON y guardar en Local Storage
window.onload = function () {
  localStorage.setItem("productos", JSON.stringify(productos));
};
