let productos = [
  {
    id: 1,
    nombre: "Alimento para perro",
    categoria: "Alimento",
    cantidad: 1,
    desc: "Alimento Royal Canin para perro adulto",
    precio: 2750,
    img: "../img/Alimento6.webp",
  },
  {
    id: 2,
    nombre: "Alimento para peces",
    categoria: "Alimento",
    cantidad: 1,
    desc: "Alimento para peces Shulet Carassius",
    precio: 1250,
    img: "../img/Alimento.webp",
  },
  {
    id: 3,
    nombre: "Alimento para perro",
    categoria: "Alimento",
    cantidad: 1,
    desc: "Alimento Proplan para perro adulto",
    precio: 3000,
    img: "../img/Alimento2.webp",
  },
  {
    id: 4,
    nombre: "Alimento para gatos",
    categoria: "Alimento",
    cantidad: 1,
    desc: "Alimento para gatos marca whiskas",
    precio: 1600,
    img: "../img/Alimento3.webp",
  },
  {
    id: 5,
    nombre: "Alimento para perro",
    categoria: "Alimento",
    cantidad: 1,
    desc: "Alimento Agility para perros adultos",
    precio: 3200,
    img: "../img/Alimento4.png",
  },
  {
    id: 6,
    nombre: "Rascador para gatos",
    categoria: "Rascador",
    cantidad: 1,
    desc: "Rascador para gatos cubierto de felpa",
    precio: 5500,
    img: "../img/Rascador.jpg",
  },
  {
    id: 7,
    nombre: "Rascador para gatos",
    categoria: "Rascador",
    cantidad: 1,
    desc: "Rascador de pared para gatos",
    precio: 2900,
    img: "../img/Rascador2.webp",
  },
  {
    id: 8,
    nombre: "Rascador para gatos",
    categoria: "Rascador",
    cantidad: 1,
    desc: "Rascador para gatos tamaño grande",
    precio: 7300,
    img: "../img/Rascador3.jpg",
  },
  {
    id: 9,
    nombre: "Juguete para ambos",
    categoria: "Juguete",
    cantidad: 1,
    desc: "Pelotita para perros y gatos",
    precio: 1800,
    img: "../img/Juguete.jpg",
  },
  {
    id: 10,
    nombre: "Juguete para perros",
    categoria: "Juguete",
    cantidad: 1,
    desc: "Hueso grande para perros",
    precio: 800,
    img: "../img/Juguete2.jpg",
  },
  {
    id: 11,
    nombre: "Juguete para gatos",
    categoria: "Juguete",
    cantidad: 1,
    desc: "Caña con plumas para gatos ",
    precio: 1000,
    img: "../img/Juguete3.webp",
  },
  {
    id: 12,
    nombre: "Juguete para gatos",
    categoria: "Juguete",
    cantidad: 1,
    desc: "Raton electrico para gatos",
    precio: 2450,
    img: "../img/Juguete4.webp",
  },
];


